name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push noetic
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: ARCH=amd64
          platforms: linux/amd64
          push: true
          tags: ripl/ur5-client-docker:main-amd64
          file: Dockerfile
      - name: Build and push noetic
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: ARCH=arm64v8
          platforms: linux/arm64/v8
          push: true
          tags: ripl/ur5-client-docker:main-arm64v8
          file: Dockerfile